### PR TITLE
PowerSupplies Inventory Spec

### PR DESCRIPTION
**Pull request by g-bougard**
PowerSupplies Inventory spec proposition to be re-used in following fusioninventory agent PRs:
 - [PR 389](https://github.com/fusioninventory/fusioninventory-agent/pull/389) from @po1vo
 - [PR 487](https://github.com/fusioninventory/fusioninventory-agent/pull/487) from @ddurieux

### CODE REVIEW

**Comment by po1vo** [comment]
I do not understand why you want the agent to inventory the elements which will not be used on the server. Like HOTREPLACEABLE, PLUGGED, STATUS.

**Comment by ddurieux** [comment]
Not agree, these information are important to know if powersupply plugged, and is hotreplaceable or not

**Comment by po1vo** [comment]
@ddurieux , the database does not have fields for those elements.

Tell me the philosophy of the agent. Is it "get every bit of data to the server and let the server deal with it"?

**Comment by trasher** [comment]
Goal is to define some specs we can use to get the job done. Point is not to grab every data, but to think about what informations would be interesting to get form the agent.

**Comment by ddurieux** [comment]
And that's elements we will add into GLPI in the future (soon :p)

**Pull request merged**
